sudo: false
language: go
go:
  - "1.11beta1"
install:
  - /usr/bin/gmake -v
  - make utilities
  - cd ${GOPATH}
  - mkdir -p src/github.com/go-home-io
  - cd src/github.com/go-home-io
  - git clone https://github.com/go-home-io/providers.git
  - cd ${TRAVIS_BUILD_DIR}
  - make dep
jobs:
  include:
    - stage: test
      script: make test
    - stage: build
      script: make build-plugins build