sudo: required
language: go
services:
  - docker
git:
  depth: 3
install: true
jobs:
  include:
    - stage: ci
      script:
        - |
          docker build -t ci --build-arg TRAVIS=$TRAVIS --build-arg TRAVIS_JOB_ID=$TRAVIS_JOB_ID \
          --build-arg TRAVIS_BRANCH=$TRAVIS_BRANCH --build-arg TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
          --build-arg BUILD_IMAGE=$BUILD_IMAGE --build-arg LINT=$LINT --build-arg RUN_IMAGE=$RUN_IMAGE \
          --build-arg INSTALL_LIBS="$INSTALL_LIBS" --build-arg C_TOKEN=$C_TOKEN .
      env:
        - BUILD_IMAGE=golang:1.11beta1-alpine3.8
        - RUN_IMAGE=alpine:3.8
        - LINT=true
        - INSTALL_LIBS='apk update && apk add make git gcc libc-dev'