sudo: required
language: go
services:
  - docker
git:
  depth: 3
before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl
install: true
jobs:
  include:
    - stage: ci
      script:
        - ./build.sh ci
      after_script:
        - curl -d "repo=github.com/go-home-io/server" https://goreportcard.com/checks
    - stage: docker-amd
      if: tag IS present
      script:
        - ./build.sh docker
    - stage: docker-arm
      if: tag IS present
      script:
        - "travis_wait 30 sleep 1800 &"
        - curl --fail --connect-timeout 60 --max-time 1800 ${RPI_BUILD_URL}/${TRAVIS_TAG}/${RPI_BUILD_KEY}