sudo: required
language: go
services:
  - docker
git:
  depth: 3
install: true
jobs:
  include:
    - stage: ci
      script:
        - echo $BUILD_IMAGE
        - docker build -t ci --build-arg BUILD_IMAGE=$BUILD_IMAGE --build-arg LINT=$LINT --build-arg RUN_IMAGE=$RUN_IMAGE --build-arg INSTALL_LIBS=$INSTALL_LIBS .
      env:
        - BUILD_IMAGE=golang:1.11beta1-alpine3.8
        - RUN_IMAGE=alpine:3.8
        - LINT=true
        - INSTALL_LIBS="apk update && apk add make git gcc libc-dev"