sudo: required
language: go
services:
  - docker
git:
  depth: 3
jobs:
  include:
    - stage: ci
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y curl make
      install:
        - nvm install 8.11.4
        - nvm use 8.11.4
      cache:
        - directories:
            - dashboard/node_modules
            - public
      script:
        - git clone https://github.com/go-home-io/dashboard db
        - cp -r db/* dashboard/
        - cd dashboard
        - make dep
        - make build
        - cd ..
        - rm -rf public
        - mkdir public
        - cp -r dashboard/build/* public/
    - ## ci stage
      script:
        - mkdir public
        - echo "ci" > public/ci.html
        - ./build.sh ci
      after_success:
        - curl -d "repo=github.com/go-home-io/server" https://goreportcard.com/checks
        - curl -d "repo=github.com/go-home-io/providers" https://goreportcard.com/checks
    - stage: docker
      if: tag IS present
      cache:
        - directories:
            - public
      script:
        - ./build.sh amd64
    - ## docker stage
      if: tag IS present
      cache:
        - directories:
            - public
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - ./build.sh arm32v7
    - stage: manifest
      if: tag IS present
      script:
        - ./build.sh manifest
