sudo: required
language: go
services:
  - docker
git:
  depth: 3
install: true
jobs:
  include:
    - stage: ci
      script:
        - ./build.sh ci
    - stage: docker
      script:
        - ./build.sh docker