[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/Knetic/govaluate"
  revision = "9aa49832a739dcd78a5542ff189fb82c3e423116"

[prune]
  go-tests = true
  unused-packages = true
